import { byId, findById } from "../utils/dom";

export const ui = {
  mainMenu: byId("mainMenu"),
  menuCards: byId("menuCardHolder"),
  menuDialog: byId("menuDialog"),
  loadingText: byId("loadingText"),
  menuNotice: byId("menuNotice"),

  enterGameButton: byId("enterGame"),
  signInButton: byId("signInButton"),
  signInHint: byId("signInHint"),
  accountRow: byId("accountRow"),
  nameInput: byId<HTMLInputElement>("nameInput", "input"),
  nameHint: byId("nameHint"),
  skinButton: byId("skinButton"),
  skinPopover: byId("skinPopover"),
  skinColorHolder: byId("skinColorHolder"),

  serverPicker: byId("serverPicker"),
  regionSelect: byId("regionSelect"),
  serverSelect: byId("serverSelect"),
  serverNote: byId("serverNote"),
  statsNote: byId("statsNote"),
  backToMain: byId("backToMain"),
  friendsNav: byId("friendsNav"),
  clanNav: byId("clanNav"),

  settingsButton: byId("settingsButton"),
  joinPartyButton: findById("joinPartyButton"),
  topLink: findById("topLink"),
  topSpot: findById("topSpot"),

  nativeResolutionToggle: byId<HTMLInputElement>("nativeResolution", "input"),
  showPingToggle: byId<HTMLInputElement>("showPing", "input"),
  showFpsToggle: byId<HTMLInputElement>("showFps", "input"),
  showCpsToggle: byId<HTMLInputElement>("showCps", "input"),
  showGridToggle: byId<HTMLInputElement>("showGrid", "input"),
  cameraLockToggle: byId<HTMLInputElement>("cameraLock", "input"),
  keybindHolder: byId("keybindHolder"),

  verifyDialog: byId("verifyDialog"),
  verifyBackdrop: byId("verifyBackdrop"),
  verifyText: byId("verifyText"),
  verifyRetry: byId("verifyRetry"),
  verifyClose: byId("verifyClose"),

  profileCard: byId("profileCard"),
  clanCard: byId("clanCard"),
  confirmCard: byId("confirmCard"),
  gameSettings: byId("gameSettings"),
  reportMenu: byId("reportMenu"),
  reportHolder: byId("reportHolder"),

  gameUI: byId("gameUI"),
  actionBar: byId("actionBar"),
  scoreDisplay: byId("scoreDisplay"),
  foodDisplay: byId("foodDisplay"),
  woodDisplay: byId("woodDisplay"),
  stoneDisplay: byId("stoneDisplay"),
  killCounter: byId("killCounter"),
  ageText: byId("ageText"),
  ageBarBody: byId("ageBarBody"),
  upgradeHolder: byId("upgradeHolder"),
  upgradeCounter: byId("upgradeCounter"),
  itemInfoHolder: byId("itemInfoHolder"),
  leaderboard: byId("leaderboard"),
  leaderboardData: byId("leaderboardData"),
  pingDisplay: byId("pingDisplay"),
  pingText: byId("pingText"),
  fpsDisplay: byId("fpsDisplay"),
  cpsDisplay: byId("cpsDisplay"),
  shutdownDisplay: byId("shutdownDisplay"),
  diedText: byId("diedText"),

  allianceButton: byId("allianceButton"),
  leaderboardButton: byId("leaderboardButton"),
  storeButton: byId("storeButton"),
  chatButton: byId("chatButton"),
  autoGatherButton: byId("autoGatherButton"),
  menuButton: byId("menuButton"),
  adminButton: byId("adminButton"),
  adminMenu: byId("adminMenu"),
  adminHolder: byId("adminHolder"),

  allianceMenu: byId("allianceMenu"),
  allianceHolder: byId("allianceHolder"),
  allianceManager: byId("allianceManager"),
  storeMenu: byId("storeMenu"),
  storeHolder: byId("storeHolder"),
  notificationDisplay: byId("noticationDisplay"),
  chatHolder: byId("chatHolder"),
  chatBox: byId<HTMLInputElement>("chatBox", "input"),
};
